[tool.poetry]
name = "balancetontexte"
version = "0.1.0"
description = ""
authors = ["SMascle <sebastien.mascle@le-campus-numerique.fr>"]

[tool.poetry.dev-dependencies]
python = "^3.8"
Flask = "^2.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
